Feature/add national service option
Healthy-London-Partnership/admin pull request #13
Opened 2020-09-23 16:39 UTC by appsol

### Add in a new "national" service option

Ref: https://trello.com/c/fDs5TiSH

- Added National field to create, edit and show views
- Added National filter to index search
- Updated Service show view to display Locations tab only if not a national service

2020-09-23 17:16 UTC, matthew-inamdar requested changes
Looks great 👍 

Minor comment to look at, but this looks good to go!

2020-09-23 17:16 UTC, matthew-inamdar commented on src/views/services/forms/DetailsTab.vue
> +          :hint="`Details if the service is only available at specific locations or can be accessed nationwide, e.g. via web or phone.`"
No need to use interpolation here.

```suggestion
          label="National?"
          hint="Details if the service is only available at specific locations or can be accessed nationwide, e.g. via web or phone."
```

2020-09-24 10:10 UTC, appsol commented on src/views/services/forms/DetailsTab.vue
> +          :hint="`Details if the service is only available at specific locations or can be accessed nationwide, e.g. via web or phone.`"
Done.

2020-09-24 12:36 UTC, matthew-inamdar requested changes
The code looks good. I did some manual testing, and when you create a service, it takes you to the `Created` page. This page asks the user to then add a service location or to go to the service page. 

Since we can't add service locations to a national service, we should instead forward the user to the service page for a newly created national service.

We would still show the `Created` page for non-national services.

2020-09-24 15:41 UTC, appsol commented
Changes completed

2020-09-25 08:58 UTC, matthew-inamdar approved these changes

2020-09-25 09:47 UTC, merged