Feature/bulk import services
Healthy-London-Partnership/admin pull request #17
Opened 2020-10-02 08:13 UTC by appsol

### Summary
https://trello.com/c/mkseo25s

- Created route and view to administer bulk imports
- Added button to Services index view
- Refactored spreadsheet import functionality to be more generic and self contained

### Development checklist
- [ ] The code has been linted `npm run lint --fix`

### Release checklist
NA

### Notes
NA

2020-10-06 21:06 UTC, matthew-inamdar requested changes
Looking good 👍 

Some comments left to take a look at.

2020-10-06 21:06 UTC, matthew-inamdar commented on src/views/organisations/forms/OrganisationSelectForm.vue
> +      this.loading = true;
There doesn't seem to be a `loading` property? It's also never set to `false` after the API request has finished.

2020-10-06 21:06 UTC, matthew-inamdar commented on src/views/services/Import.vue
> +            console.log(error.request);
Can we make these `console.error()` instead?

2020-10-06 21:06 UTC, matthew-inamdar commented on src/views/services/Import.vue
> +    async onSubmit() {
This is `async` but there is no `await` in the body?

2020-10-07 17:04 UTC, appsol commented on src/views/services/Import.vue
> +            console.log(error.request);
done

2020-10-07 17:04 UTC, appsol commented on src/views/services/Import.vue
> +    async onSubmit() {
Sorry my bad. Changed to then...catch style of promise handling but forgot to take the async off the function.

2020-10-07 17:05 UTC, appsol commented on src/views/organisations/forms/OrganisationSelectForm.vue
> +      this.loading = true;
Sorry, added loading to data and made select dependant on !loading.

2020-10-07 21:09 UTC, matthew-inamdar commented on src/views/services/Import.vue
> +    async onSubmit() {
Cool - looks good 🙂

2020-10-07 21:10 UTC, matthew-inamdar approved these changes

2020-10-08 19:56 UTC, merged